### ISSUE TITLE
Question: how to get the base64 blob of a generated Certificate

### ISSUE THREAD

**Issue by git-noise** [obelisk/sshcerts#13]
Hello and many thanks for the project,

I have a quick question for you, what would you say is the best way to retrieve the base64 blob of a generated Certificate?

I see you can get it via ```println!``` as the ```fmt:Display``` trait is implemented, but it does not necessarily make it too friendly to do some post-processing on the data. Additionally - and I still need to debug that part - all the print done outside of main seem to make the ```macro.rs``` complain.

Did I miss another function that allow you to get it?

Many thanks,

Best,

**Comment by obelisk** [comment]
The general way I expected people to get the certificate is to use the `format!` macro like so:

```rust
let cert = Certificate::from_path(..);
let serialized_certificate = format!("{:#}", cert);
```

**Comment by obelisk** [comment]
If you want direct access to just the base64 encoded certificate, the `serialized` member of the `Certificate` struct is also available and a base64 of that is a valid certificate without the type (at the beginning) or comment (at the end)
