### ISSUE TITLE
from_bytes() equivalent for Certificates

### ISSUE THREAD

**Issue by 1Dragoon** [obelisk/sshcerts#16]
I noticed the PublicKey struct has a from_bytes, is there an equivalent for the Certificate struct? Basically a way to receive the from the SSH wire protocol for an SSH agent. I've started to write my own method but I somewhat feel like I may be reinventing the wheel because I'm not understanding some existing functionality or something about the protocol in general.

**Comment by 1Dragoon** [comment]
Submitted PR #17 so you have an idea of what I'm talking about

**Comment by obelisk** [comment]
Heyo thanks for the PR, reviewing it now!
